# Generated by Django 5.1.5 on 2025-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('EXERCISE', 'Exercício'), ('HEALTH', 'Saúde'), ('LEARNING', 'Aprendizado'), ('WORK', 'Trabalho'), ('LEISURE', 'Lazer')], default='EXERCISE', max_length=20),
        ),
    ]
